# Generated by Django 4.2.23 on 2025-07-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('service_required', models.CharField(choices=[('Custom Website Development', 'Custom Website Development'), ('Website Maintenance', 'Website Maintenance'), ('Hosting Services', 'Hosting Services'), ('design', 'UI/UX Design'), ('SEO Optimization', 'SEO Optimization'), ('other', 'Other')], max_length=50)),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
